CREATE VIEW RequestsPending
AS
SELECT REQUESTS.ID,TITLEMESSAGE,ESTATUS, INITIALIMAGE, IMAGEMIMETYPE, NAME,EMAIL,PHONE, ADDRESS, INITIALDATE ,DESCRIPTION
FROM REQUESTS INNER JOIN TITLES ON REQUESTS.ID=TITLES.ID_REQUEST
INNER JOIN CONTACTS ON REQUESTS.ID=CONTACTS.ID_REQUEST
WHERE REQUESTS.ESTATUS IN('Pending','In progress'); 