//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestorationStore.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Respons
    {
        public Respons()
        {
            this.Commentaries = new HashSet<Commentary>();
        }
    
        public int Id { get; set; }
        public int Id_Request { get; set; }
        public decimal Cost { get; set; }
        public string Description { get; set; }
        public System.DateTime FinalDate { get; set; }
        public byte[] FinalImage { get; set; }
    
        public virtual ICollection<Commentary> Commentaries { get; set; }
        public virtual Request Request { get; set; }
    }
}
