//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestorationStore.Domain.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RestorationStoreBDEntities : DbContext
    {
        public RestorationStoreBDEntities()
            : base("name=RestorationStoreBDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Request> Requests { get; set; }
        public DbSet<Title> Titles { get; set; }
        public DbSet<Commentary> Commentaries { get; set; }
        public DbSet<Contact> Contacts { get; set; }
        public DbSet<Respons> Responses { get; set; }
        public DbSet<RequestsPending> RequestsPendings { get; set; }
    }
}
